Containerize development environment#1
SansSeryph/PomoNotes pull request #2
Opened 2020-12-12 16:03 UTC by carlschroedl

Addresses #1

2020-12-12 16:04 UTC, carlschroedl commented
@BeckyAndresen

2020-12-17 04:43 UTC, SansSeryph requested changes
This is interesting! I don't quite understand how all of this works but it looks like something that could be really helpful!

One request I have is to add link the Docker README from the main project README.

2020-12-17 04:43 UTC, SansSeryph commented on .devcontainer/Dockerfile
> +RUN gem install rails webdrivers
Does this grab the version of Rails that's in the Gemfile?

2020-12-17 04:43 UTC, SansSeryph commented on .devcontainer/Dockerfile
> +FROM mcr.microsoft.com/vscode/devcontainers/ruby:${VARIANT}
This project is set to use Ruby 2.7 (see `.ruby-version` and `Gemfile` in the project). Will this grab the correct version?

2020-12-17 04:43 UTC, SansSeryph commented on .devcontainer/docker-compose.yml
> +      MYSQL_PASSWORD: userpassword
The project isn't currently set up to use any database (default is sqlite3). We may have to make some tweaks when we begin using the ORM

2020-12-18 03:51 UTC, carlschroedl commented on .devcontainer/Dockerfile
> +RUN gem install rails webdrivers
Nope! Nice catch. I removed it.

2020-12-18 03:53 UTC, carlschroedl commented on .devcontainer/Dockerfile
> +FROM mcr.microsoft.com/vscode/devcontainers/ruby:${VARIANT}
It gets really close by default. I changed the default to 2.7.2 and through documentation encouraged users to use rvm to install the version in `.ruby-version`.

2020-12-18 03:56 UTC, carlschroedl commented on .devcontainer/docker-compose.yml
> +      MYSQL_PASSWORD: userpassword
Yeah, the db container isn't used right now. If it's relevant to start using MySQL soon, this would make it easy to do so. If that's a long ways off, this could be removed and re-introduced latorz.

2020-12-18 04:00 UTC, carlschroedl commented on spec/support/capybara_helper.rb
> -Capybara.javascript_driver = :selenium_chrome_headless
Chrome needs to be started with non-default options to work in a headless environment like a CI runner or the dev container. Copied from: https://dev.to/fdoxyz/headless-chrome-dual-mode-tests-for-ruby-on-rails-4p6g

2020-12-18 04:01 UTC, carlschroedl commented on spec/support/capybara_helper.rb
> -Capybara.javascript_driver = :selenium_chrome_headless
Ah, I don't know how to lint or do other static analysis things yet in rubytown. Plz Let me know if this needs to be de-mess-ified before merging!

2020-12-18 16:36 UTC, SansSeryph commented on spec/support/capybara_helper.rb
> -Capybara.javascript_driver = :selenium_chrome_headless
For linting/fixing Ruby, [ruby-rubocop](https://marketplace.visualstudio.com/items?itemName=misogi.ruby-rubocop) is great. It'll use the `.rubocop.yml` to generate rules. Documentation can be found here: https://docs.rubocop.org/rubocop/index.html

I also recommend [Ruby Solargraph](https://marketplace.visualstudio.com/items?itemName=castwide.solargraph) if you want an LSP. :)

2020-12-18 16:41 UTC, SansSeryph approved these changes
I do have one question: It doesn't seem like it but there are some gems in `Gemfile` that are needed for dev. Would it make sense to install them as the container is getting set up?

2020-12-20 23:46 UTC, carlschroedl commented on .devcontainer/docker-compose.yml
> +      MYSQL_PASSWORD: userpassword
removed it!

2020-12-22 20:19 UTC, SansSeryph commented on spec/support/capybara_helper.rb
> +  end
Just to understand your intentions here, do you want the user to manually set `HEADLESS` to something in order to get `:chrome` as a driver?

2020-12-22 20:19 UTC, SansSeryph commented on spec/support/capybara_helper.rb
> +  end
Selenium already offers a lot of these things so I'm not sure how these changes help. Are there compatibility issues between Selenium and Docker?

2020-12-31 21:28 UTC, carlschroedl commented on spec/support/capybara_helper.rb
> +  end
Yep! To help clarify things I added a link to the blog post this is copied from. I also copied + pasted and tweaked the most relevant part of the blog post and embedded it as a comment here. Does that clear things up?

2020-12-31 22:11 UTC, carlschroedl commented on spec/support/capybara_helper.rb
> +  end
Yeah, kind of -- it's less about Docker and more about headless vs. headful (<--totally a word!) environments. It gets touched on briefly in [the blog post](https://dev.to/fdoxyz/headless-chrome-dual-mode-tests-for-ruby-on-rails-4p6g#usage) that this code is copied from. I'll try to elaborate a bit. By default Selenium starts up Chrome with options that work really well in a desktop/laptop environment that has all kinds of GUI dependencies installed in it. However, both continuous integration servers and this local containerized development environment lack those GUI-centric goodies. This file ensures that Selenium can start up Chrome with options that prevent Chrome from crashing in a headless environment like a CI server or a containerized development environment.

For example, if I run tests in a headless environment right now in the main branch, all tests fail due to Chrome crashing.
```bash
vscode ➜ /workspace (main) $ bundle exec rspec
Capybara starting Puma...
* Version 4.3.6 , codename: Mysterious Traveller
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:32771
FFFF**

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Timer has a start button that counts down after start button is clicked and has the correct time after 1 second
     # No reason given
     # ./spec/features/timer_spec.rb:37

  2) Timer has a start button that counts down after start button is clicked and has the correct time after 5 seconds
     # No reason given
     # ./spec/features/timer_spec.rb:42


Failures:

  1) Timer has a default timer of 40 minutes
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: before { visit root_path }
          
          Selenium::WebDriver::Error::UnknownError:
            unknown error: Chrome failed to start: crashed.
              (unknown error: DevToolsActivePort file doesn't exist)
              (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
          # #0 0x5567d1c30e79 <unknown>
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:102:in `create_session'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:56:in `handshake'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/chrome/driver.rb:43:in `initialize'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:46:in `new'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:46:in `for'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver.rb:88:in `for'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/capybara-3.33.0/lib/capybara/selenium/driver.rb:52:in `browser'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/capybara-3.33.0/lib/capybara/selenium/driver.rb:71:in `visit'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/capybara-3.33.0/lib/capybara/session.rb:278:in `visit'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/capybara-3.33.0/lib/capybara/dsl.rb:53:in `call'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/capybara-3.33.0/lib/capybara/dsl.rb:53:in `visit'
          # ./spec/features/timer_spec.rb:7:in `block (2 levels) in <top (required)>'

     1.2) Failure/Error: Unable to infer file and line number from backtrace
          
          Selenium::WebDriver::Error::UnknownError:
            unknown error: Chrome failed to start: crashed.
              (unknown error: DevToolsActivePort file doesn't exist)
              (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
          # #0 0x5567d1c30e79 <unknown>
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:102:in `create_session'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:56:in `handshake'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/chrome/driver.rb:43:in `initialize'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:46:in `new'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:46:in `for'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver.rb:88:in `for'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/capybara-3.33.0/lib/capybara/selenium/driver.rb:52:in `browser'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/capybara-3.33.0/lib/capybara/selenium/driver.rb:97:in `current_url'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/capybara-3.33.0/lib/capybara/session.rb:229:in `current_url'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/capybara-screenshot-1.0.25/lib/capybara-screenshot/rspec.rb:56:in `block in after_failed_example'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/capybara-3.33.0/lib/capybara.rb:371:in `using_session'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/capybara-screenshot-1.0.25/lib/capybara-screenshot/capybara.rb:7:in `using_session'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/capybara-screenshot-1.0.25/lib/capybara-screenshot/rspec.rb:55:in `after_failed_example'
          # /usr/local/rvm/gems/ruby-2.7.2/gems/capybara-screenshot-1.0.25/lib/capybara-screenshot/rspec.rb:105:in `block (2 levels) in <main>'
...
```

While most of the changes in this pull request focus solely on enabling a containerized development environment, this particular file would support running Selenium tests in both a containerized development environment and on a continuous integration server.

2021-01-03 19:22 UTC, BeckyAndresen commented on .devcontainer/README.md
> +    ```http://localhost:3000```
These steps work for me!

2021-01-03 19:27 UTC, BeckyAndresen commented on .devcontainer/devcontainer.json
> +	"name": "PomoNotes",
@carlschroedl Could you please fix the indentation here?

2021-01-03 20:01 UTC, BeckyAndresen approved these changes

2021-01-03 20:04 UTC, SansSeryph approved these changes

2021-01-03 20:05 UTC, BeckyAndresen approved these changes

2021-01-03 20:20 UTC, merged